# Generated by Django 2.2.8 on 2021-03-11 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Declarations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], max_length=60)),
                ('party_name', models.CharField(max_length=70)),
                ('party_address', models.TextField(blank=True, help_text='Enter Home/Office Address')),
                ('party_agent', models.TextField(blank=True, help_text='Enter Name of Agent')),
            ],
        ),
        migrations.CreateModel(
            name='RiskName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RiskDetails',
            fields=[
                ('risk_duration', models.CharField(choices=[('', 'Select Duration'), ('ONE MONTH', 'ONE MONTH'), ('THREE MONTHS', 'THREE MONTHS'), ('SIX MONTHS', 'SIX MONTHS'), ('A YEAR', 'A YEAR')], max_length=100)),
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('risk_amount', models.PositiveIntegerField()),
                ('risk_active_date', models.DateTimeField(blank=True, null=True)),
                ('risk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskName')),
            ],
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_description', models.TextField()),
                ('coverage_limit', models.PositiveIntegerField()),
                ('coverage_premium', models.PositiveIntegerField()),
                ('coverage_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskName')),
            ],
        ),
    ]
