# Generated by Django 2.2.8 on 2021-03-15 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20210315_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdetails',
            name='risk_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.RiskName', to_field='name'),
        ),
    ]
